# Assignment 3

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('creditcard.csv')
df

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [4]:
x=df.drop('Class',axis=1)
y=df['Class']

In [5]:
#normalizing data
x=(x-x.mean())/x.std()

In [6]:
x

Time        V1        V2        V3        V4        V5        V6  \
0      -1.996580 -0.694241 -0.044075  1.672771  0.973364 -0.245116  0.347067   
1      -1.996580  0.608495  0.161176  0.109797  0.316522  0.043483 -0.061820   
2      -1.996558 -0.693499 -0.811576  1.169466  0.268231 -0.364571  1.351451   
3      -1.996558 -0.493324 -0.112169  1.182514 -0.609726 -0.007469  0.936148   
4      -1.996537 -0.591329  0.531540  1.021410  0.284655 -0.295015  0.071998   
...          ...       ...       ...       ...       ...       ...       ...   
284802  1.641929 -6.065831  6.099275 -6.486233 -1.459638 -3.886604 -1.956687   
284803  1.641950 -0.374121 -0.033356  1.342142 -0.521651  0.629039  0.794444   
284804  1.641971  0.980022 -0.182433 -2.143201 -0.393983  1.905830  2.275258   
284805  1.641971 -0.122755  0.321250  0.463319  0.487192 -0.273836  0.468154   
284806  1.642055 -0.272330 -0.114899  0.463865 -0.357569 -0.009089 -0.487601   

              V7        V8        V9  ...       V20       V21       V22  \
0       0.193679  0.082637  0.331127  ...  0.326117 -0.024923  0.382854   
1      -0.063700  0.071253 -0.232494  ... -0.089611 -0.307376 -0.880075   
2       0.639775  0.207372 -1.378673  ...  0.680974  0.337631  1.063356   
3       0.192070  0.316017 -1.262501  ... -0.269855 -0.147443  0.007267   
4       0.479301 -0.226510  0.744325  ...  0.529938 -0.012839  1.100009   
...          ...       ...       ...  ...       ...       ...       ...   
284802 -3.975621  6.116562  1.742556  ...  1.914361  0.290602  0.154146   
284803  0.019667  0.246886  0.532298  ...  0.077330  0.291625  1.273779   
284804 -0.239939  0.593139  0.393630  ...  0.001811  0.315912  0.796786   
284805 -0.554671  0.568630  0.356886  ...  0.165299  0.361111  1.102449   
284806  1.274767 -0.347176  0.442532  ...  0.496738  0.355410  0.886147   

             V23       V24       V25       V26       V27       V28    Amount  
0      -0.176911  0.110507  0.246585 -0.392170  0.330891 -0.063781  0.244964  
1       0.162201 -0.561130  0.320693  0.261069 -0.022256  0.044607 -0.342474  
2       1.456317 -1.138090 -0.628536 -0.288446 -0.137137 -0.181021  1.160684  
3      -0.304776 -1.941024  1.241902 -0.460217  0.155396  0.186188  0.140534  
4      -0.220123  0.233250 -0.395201  1.041609  0.543619  0.651815 -0.073403  
...          ...       ...       ...       ...       ...       ...       ...  
284802  1.624571 -0.840999  2.756316  0.518499  2.337897  2.495525 -0.350150  
284803  0.019958 -1.677917 -1.163724 -0.819645  0.169641 -0.162163 -0.254116  
284804 -0.060053  1.056942  0.509796 -0.181181  0.011037 -0.080467 -0.081839  
284805 -0.261503  0.203427 -1.091853  1.133633  0.269604  0.316686 -0.313248  
284806  0.603364  0.014526 -0.908630 -1.696850 -0.005984  0.041350  0.514354  

[284807 rows x 30 columns]

In [8]:
# Before applying SMOTE Oversampling

In [9]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y)

In [10]:
xtrain.shape

(213605, 30)

In [11]:
from sklearn.ensemble import RandomForestClassifier
R=RandomForestClassifier()

In [12]:
R.fit(xtrain,ytrain)

RandomForestClassifier()

In [13]:
pred=R.predict(xtest)

In [14]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [15]:
a1=accuracy_score(ytest,pred)
a1

0.9996207971686188

In [16]:
m1=confusion_matrix(ytest,pred)
m1

array([[71078,     1],
       [   26,    97]], dtype=int64)

In [17]:
cl1=classification_report(ytest,pred)
print(cl1)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     71079
           1       0.99      0.79      0.88       123

    accuracy                           1.00     71202
   macro avg       0.99      0.89      0.94     71202
weighted avg       1.00      1.00      1.00     71202



In [18]:
# After applying SMOTE Oversampling

In [19]:
from imblearn.over_sampling import SMOTE

In [20]:
oversample=SMOTE()

In [21]:
X,Y=oversample.fit_resample(x,y)

In [22]:
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,Y)

In [23]:
Xtrain.shape

(426472, 30)

In [24]:
R1=RandomForestClassifier()

In [25]:
R1.fit(Xtrain,Ytrain)

RandomForestClassifier()

In [29]:
pred1=R1.predict(Xtest)

In [30]:
a2=accuracy_score(Ytest,pred1)
a2

0.9999085524557183

In [31]:
m2=confusion_matrix(Ytest,pred1)
m2

array([[71331,    13],
       [    0, 70814]], dtype=int64)

In [32]:
cl2=classification_report(Ytest,pred1)
print(cl2)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     71344
           1       1.00      1.00      1.00     70814

    accuracy                           1.00    142158
   macro avg       1.00      1.00      1.00    142158
weighted avg       1.00      1.00      1.00    142158



In [37]:
#comparision before and after oversampling

In [38]:
print('Accuracy before applying SMOTE: ',a1)
print('\nAccuracy after applying SMOTE: ',a2)

Accuracy before applying SMOTE:  0.9996207971686188

Accuracy after applying SMOTE:  0.9999085524557183


In [39]:
print('Before applying SMOTE\n',m1,'\n\nAfter applying SMOTE\n',m2)

Before applying SMOTE
 [[71078     1]
 [   26    97]] 

After applying SMOTE
 [[71331    13]
 [    0 70814]]


In [40]:
print('Before applying SMOTE\n',cl1,'\nAfter applying SMOTE\n',cl2)

Before applying SMOTE
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     71079
           1       0.99      0.79      0.88       123

    accuracy                           1.00     71202
   macro avg       0.99      0.89      0.94     71202
weighted avg       1.00      1.00      1.00     71202
 
After applying SMOTE
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     71344
           1       1.00      1.00      1.00     70814

    accuracy                           1.00    142158
   macro avg       1.00      1.00      1.00    142158
weighted avg       1.00      1.00      1.00    142158

